// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wdjrQSNRX7ys49KwqunuZ4
// Component: zx7pWZEV_fAX
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 7oMbG7rPxeuI/component
import Footer from "../../Footer"; // plasmic-import: t96iChT22ax_/component
import { useScreenVariants as useScreenVariantshbagvQWqcZ69 } from "../website_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: HbagvQWqcZ69/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../website_starter/plasmic_website_starter.module.css"; // plasmic-import: wdjrQSNRX7ys49KwqunuZ4/projectcss
import sty from "./PlasmicMtnData.module.css"; // plasmic-import: zx7pWZEV_fAX/css
import mtnDaily30MbR5PngYu3UYsjCpQrs from "./images/mtnDaily30MbR5Png.png"; // plasmic-import: yu3UYsjCPQrs/picture
import mtnDaily100MbR10PngEOq9YJhLxDmJ from "./images/mtnDaily100MbR10Png.png"; // plasmic-import: EOq9YJhLXDmJ/picture
import mtnDaily200MbR15PngT16W5PmfBjbi from "./images/mtnDaily200MbR15Png.png"; // plasmic-import: T16W5PmfBjbi/picture
import mtnDaily300MbR20PngZcT7S40BG1Y from "./images/mtnDaily300MbR20Png.png"; // plasmic-import: ZcT-7s40bG1y/picture
import mtnDaily1GbR29PngRdLQp5UrnSyc from "./images/mtnDaily1GbR29Png.png"; // plasmic-import: RdLQp5URNSyc/picture
import mtnWeekly20MbR5PngBK5Pu4OsygO2 from "./images/mtnWeekly20MbR5Png.png"; // plasmic-import: bK5Pu4OsygO2/picture
import mtnWeekly60MbR10PngB19RacrS64E from "./images/mtnWeekly60MbR10Png.png"; // plasmic-import: b19RacrS64E_/picture
import mtnWeekly70MbR12PngWyLxi5MQYgT from "./images/mtnWeekly70MbR12Png.png"; // plasmic-import: Wy_LXI5mQYgT/picture
import mtnWeekly100MbR15100MbpngARk8REwpMOr from "./images/mtnWeekly100MbR15100Mbpng.png"; // plasmic-import: aRK8R_ewpMOr/picture
import mtnWeekly100MbR17120MbpngRQmYkJCpf7Lv from "./images/mtnWeekly100MbR17120Mbpng.png"; // plasmic-import: rQmYkJCpf7lv/picture
import mtnWeekly200MbR25PngCXLz0DalLxs from "./images/mtnWeekly200MbR25Png.png"; // plasmic-import: _cXLz0dalLXS/picture
import mtnWeekly400MbR40Png4GRIlyOh0Wfc from "./images/mtnWeekly400MbR40Png.png"; // plasmic-import: 4gRIlyOh0WFC/picture
import mtnWeekly500R49PngTUjoQcn67HXn from "./images/mtnWeekly500R49Png.png"; // plasmic-import: TUjoQcn67hXn/picture
import mtnWeekly1GbR70PngERfeBkCgSvus from "./images/mtnWeekly1GbR70Png.png"; // plasmic-import: eRfeBKCgSVUS/picture
import mtnWeekly2GbR99PngZx0O07Pi8KZd from "./images/mtnWeekly2GbR99Png.png"; // plasmic-import: zx0o07PI8KZd/picture
import mtnMonthly3GbR199PngOzwS4EPEsdIx from "./images/mtnMonthly3GbR199Png.png"; // plasmic-import: ozwS4ePEsdIx/picture

createPlasmicElementProxy;

export const PlasmicMtnData__VariantProps = new Array();

export const PlasmicMtnData__ArgProps = new Array();

function PlasmicMtnData__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshbagvQWqcZ69()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"shop"}
          data-plasmic-override={overrides.shop}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.shop
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <section className={classNames(projectcss.all, sty.section__xiv1D)}>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#2E2854" }}
                      >
                        {"MTN Data"}
                      </span>
                    </React.Fragment>
                  </h1>
                }

                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__uMrn7)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__oPFcX)}
            >
              <div className={classNames(projectcss.all, sty.column__pmBcq)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gqzz4)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: mtnDaily30MbR5PngYu3UYsjCpQrs,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__fmCr8)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gkIsf)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnDaily100MbR10PngEOq9YJhLxDmJ,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__rmOse)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rPGtp)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnDaily200MbR15PngT16W5PmfBjbi,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__c2UHy)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zy08)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnDaily300MbR20PngZcT7S40BG1Y,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__fPq63)}
            >
              <div className={classNames(projectcss.all, sty.column__tYlCb)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__b3FhA)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: mtnDaily1GbR29PngRdLQp5UrnSyc,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__jF2Wq)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nJPj9)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly20MbR5PngBK5Pu4OsygO2,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__oqgx8)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cNomb)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly60MbR10PngB19RacrS64E,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___8Rbna)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__p2R6R)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly70MbR12PngWyLxi5MQYgT,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___7Ladi)}
            >
              <div className={classNames(projectcss.all, sty.column__m6Sxf)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__c03Mh)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly100MbR15100MbpngARk8REwpMOr,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__oUS)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__agh6Y)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly100MbR17120MbpngRQmYkJCpf7Lv,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___80EiB)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__i8Wia)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly200MbR25PngCXLz0DalLxs,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__tiCJn)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__kj7Ci)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly400MbR40Png4GRIlyOh0Wfc,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__yCxCl)}
            >
              <div className={classNames(projectcss.all, sty.column__ysCyd)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__m1ShS)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly500R49PngTUjoQcn67HXn,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__i8BC0)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dQizb)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly1GbR70PngERfeBkCgSvus,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__nwep)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__aLfE)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWeekly2GbR99PngZx0O07Pi8KZd,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__shbVq)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__w08Wl)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnMonthly3GbR199PngOzwS4EPEsdIx,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  shop: ["shop", "header", "text", "h1", "footer"],
  header: ["header"],
  text: ["text", "h1"],
  h1: ["h1"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMtnData__ArgProps,
          internalVariantPropNames: PlasmicMtnData__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMtnData__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "shop") {
    func.displayName = "PlasmicMtnData";
  } else {
    func.displayName = `PlasmicMtnData.${nodeName}`;
  }
  return func;
}

export const PlasmicMtnData = Object.assign(
  // Top-level PlasmicMtnData renders the root element
  makeNodeComponent("shop"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    text: makeNodeComponent("text"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicMtnData
    internalVariantProps: PlasmicMtnData__VariantProps,
    internalArgProps: PlasmicMtnData__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "MTN Data",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicMtnData;
/* prettier-ignore-end */
