// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wdjrQSNRX7ys49KwqunuZ4
// Component: 663kqNhK3bea
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 7oMbG7rPxeuI/component
import Footer from "../../Footer"; // plasmic-import: t96iChT22ax_/component
import { useScreenVariants as useScreenVariantshbagvQWqcZ69 } from "../website_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: HbagvQWqcZ69/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../website_starter/plasmic_website_starter.module.css"; // plasmic-import: wdjrQSNRX7ys49KwqunuZ4/projectcss
import sty from "./PlasmicTelkomSocials.module.css"; // plasmic-import: 663kqNhK3bea/css
import telkomMobileWeeklySocialR55PngUKq1Nv9IeAWi from "./images/telkomMobileWeeklySocialR55Png.png"; // plasmic-import: UKq1nv9IeAWi/picture
import telkomMobileWeeklySocialR9PngLdLc8SwtOiV from "./images/telkomMobileWeeklySocialR9Png.png"; // plasmic-import: LDLc8SWTOi_V/picture
import telkomMobileWeeklySocialR12PngCoV7HOsMooF from "./images/telkomMobileWeeklySocialR12Png.png"; // plasmic-import: CO_V7hOSMooF/picture
import telkomMobileWeeklySocialR19PngV4KDnCs8Yb7U from "./images/telkomMobileWeeklySocialR19Png.png"; // plasmic-import: V4KDnCs8YB7U/picture
import telkomMobileWeeklySocialR36PngWZcZhmkNnMwn from "./images/telkomMobileWeeklySocialR36Png.png"; // plasmic-import: wZcZhmkNnMWN/picture
import telkomMobileWeeklySocialR60PngNb4CBbf88Qv7 from "./images/telkomMobileWeeklySocialR60Png.png"; // plasmic-import: nb4cBBF88qv7/picture
import telkomTikTok1DayR5PngYwzCslSqVg1 from "./images/telkomTikTok1DayR5Png.png"; // plasmic-import: YWZCsl-sqVG1/picture
import telkomTikTok1DayR10PngEssbbPj6AmdP from "./images/telkomTikTok1DayR10Png.png"; // plasmic-import: essbbPj6amdP/picture
import telkomTikTok7DaysR14Png28RP2K2YRw from "./images/telkomTikTok7DaysR14Png.png"; // plasmic-import: 2_8R-p2K2YRw/picture
import telkomTikTok7DaysR20PngNdnCtE3Zuh9G from "./images/telkomTikTok7DaysR20Png.png"; // plasmic-import: NDNCtE3Zuh9g/picture
import r35JpgM21OsYgmCmXp from "./images/r35Jpg.jpg"; // plasmic-import: M21osYgmCmXp/picture
import telkomTikTokWeekendR10CopypngUDsxgGjhsJvZ from "./images/telkomTikTokWeekendR10Copypng.png"; // plasmic-import: uDsxgGJHSJvZ/picture
import telkomTikTokWeekendR15PngCCyNvmF1AbTz from "./images/telkomTikTokWeekendR15Png.png"; // plasmic-import: CCyNvmF1ABTz/picture
import telkomVoiceR5PngV0LUuYgYox from "./images/telkomVoiceR5Png.png"; // plasmic-import: v0L_uu_YgYox/picture
import telkomVoiceR9Png75MFVLoYaY from "./images/telkomVoiceR9Png.png"; // plasmic-import: 75mF_v_LoYaY/picture
import telkomVoiceR15PngVHlppBtskTAl from "./images/telkomVoiceR15Png.png"; // plasmic-import: vHLPPBtskTAl/picture
import telkomVoiceR30PngHbnLIhudbE7T from "./images/telkomVoiceR30Png.png"; // plasmic-import: hbnLIhudbE7t/picture
import telkomWhatsAppDailyR5PngS0EAe9P81ZUh from "./images/telkomWhatsAppDailyR5Png.png"; // plasmic-import: s0eAe9P81zUh/picture
import telkomWhatsAppDailyR10PngBhNVkMVpQba1 from "./images/telkomWhatsAppDailyR10Png.png"; // plasmic-import: bhNVkMVpQba1/picture
import telkomWhatsAppDailyR15PngH03ZtxY8En4H from "./images/telkomWhatsAppDailyR15Png.png"; // plasmic-import: h03ZtxY8EN4h/picture

createPlasmicElementProxy;

export const PlasmicTelkomSocials__VariantProps = new Array();

export const PlasmicTelkomSocials__ArgProps = new Array();

function PlasmicTelkomSocials__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshbagvQWqcZ69()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"shop"}
          data-plasmic-override={overrides.shop}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.shop
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <section className={classNames(projectcss.all, sty.section__slfoO)}>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#2E2854" }}
                      >
                        {"Telkom Socials"}
                      </span>
                    </React.Fragment>
                  </h1>
                }

                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__suC2X)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__xu52Z)}
            >
              <div className={classNames(projectcss.all, sty.column__uxrsz)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__qzD3T)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: telkomMobileWeeklySocialR55PngUKq1Nv9IeAWi,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__jIamH)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___3Iwym)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomMobileWeeklySocialR9PngLdLc8SwtOiV,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__t8QIi)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___2TY7I)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomMobileWeeklySocialR12PngCoV7HOsMooF,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__e7Yo1)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rCB)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomMobileWeeklySocialR19PngV4KDnCs8Yb7U,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__jUdMi)}
            >
              <div className={classNames(projectcss.all, sty.column__m9Cj2)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__tgqaf)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: telkomMobileWeeklySocialR36PngWZcZhmkNnMwn,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__pcLnh)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rf4Fu)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomMobileWeeklySocialR60PngNb4CBbf88Qv7,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___95En8)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mz1C)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomTikTok1DayR5PngYwzCslSqVg1,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__zHsa)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__yOvI)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomTikTok1DayR10PngEssbbPj6AmdP,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ty1)}
            >
              <div className={classNames(projectcss.all, sty.column__gMsL)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__jwOjO)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: telkomTikTok7DaysR14Png28RP2K2YRw,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__fYtxH)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__f6YQ7)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomTikTok7DaysR20PngNdnCtE3Zuh9G,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__gu4S)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vFzxB)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: r35JpgM21OsYgmCmXp,
                    fullWidth: 1276,
                    fullHeight: 1273,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wt4Xn)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__jJria)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomTikTokWeekendR10CopypngUDsxgGjhsJvZ,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__cztDp)}
            >
              <div className={classNames(projectcss.all, sty.column__woy7B)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mPYsl)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: telkomTikTokWeekendR15PngCCyNvmF1AbTz,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__uFyCk)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__jo7Bg)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomVoiceR5PngV0LUuYgYox,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___2X2Of)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ynr9I)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomVoiceR9Png75MFVLoYaY,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__zokPt)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fw6O)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomVoiceR15PngVHlppBtskTAl,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__kc2Jr)}
            >
              <div className={classNames(projectcss.all, sty.column__dCBp9)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__jjl37)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: telkomVoiceR30PngHbnLIhudbE7T,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wY2Yr)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ntTW)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomWhatsAppDailyR5PngS0EAe9P81ZUh,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__e763S)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__tBeD7)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomWhatsAppDailyR10PngBhNVkMVpQba1,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__blOq6)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__qssll)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: telkomWhatsAppDailyR15PngH03ZtxY8En4H,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__wcdeW)}
            >
              <div className={classNames(projectcss.all, sty.column__kVyEg)} />
              <div className={classNames(projectcss.all, sty.column___0MBzl)} />
              <div className={classNames(projectcss.all, sty.column__cOiN)} />
              <div className={classNames(projectcss.all, sty.column__y1Xd7)} />
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__s2X5P)}
            >
              <div className={classNames(projectcss.all, sty.column___1Dbp4)} />
              <div className={classNames(projectcss.all, sty.column__sodNy)} />
              <div className={classNames(projectcss.all, sty.column__ppgba)} />
              <div className={classNames(projectcss.all, sty.column__inz0A)} />
            </p.Stack>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  shop: ["shop", "header", "text", "h1", "footer"],
  header: ["header"],
  text: ["text", "h1"],
  h1: ["h1"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTelkomSocials__ArgProps,
          internalVariantPropNames: PlasmicTelkomSocials__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTelkomSocials__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "shop") {
    func.displayName = "PlasmicTelkomSocials";
  } else {
    func.displayName = `PlasmicTelkomSocials.${nodeName}`;
  }
  return func;
}

export const PlasmicTelkomSocials = Object.assign(
  // Top-level PlasmicTelkomSocials renders the root element
  makeNodeComponent("shop"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    text: makeNodeComponent("text"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicTelkomSocials
    internalVariantProps: PlasmicTelkomSocials__VariantProps,
    internalArgProps: PlasmicTelkomSocials__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Telkom Social Bundles",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTelkomSocials;
/* prettier-ignore-end */
