// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wdjrQSNRX7ys49KwqunuZ4
// Component: 0nI1LDWjVWhE
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 7oMbG7rPxeuI/component
import Footer from "../../Footer"; // plasmic-import: t96iChT22ax_/component
import { useScreenVariants as useScreenVariantshbagvQWqcZ69 } from "../website_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: HbagvQWqcZ69/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../website_starter/plasmic_website_starter.module.css"; // plasmic-import: wdjrQSNRX7ys49KwqunuZ4/projectcss
import sty from "./PlasmicMtnSocialBundles.module.css"; // plasmic-import: 0nI1LDWjVWhE/css
import mtnWhatsAppDailypng2GjKo6Dzf507 from "./images/mtnWhatsAppDailypng.png"; // plasmic-import: 2GjKO6Dzf507/picture
import mtnWhatsAppWeekly300MbR12PngMtFiWaHg96SR from "./images/mtnWhatsAppWeekly300MbR12Png.png"; // plasmic-import: MtFiWAHg96sR/picture
import mtnWhatsAppWeekly1GbR25PngMlv7YaIbPbvU from "./images/mtnWhatsAppWeekly1GbR25Png.png"; // plasmic-import: MLV7YAIbPbvU/picture
import mtnWhatsAppMonthly1GbR40PngYwk3UJdOTuPv from "./images/mtnWhatsAppMonthly1GbR40Png.png"; // plasmic-import: YWK3UJdOTuPv/picture
import mtnFacebookDaily200R5PngQyokoGuqQlYs from "./images/mtnFacebookDaily200R5Png.png"; // plasmic-import: QyokoGuqQlYS/picture
import mtnFacebookDaily1GbR20PngCTbGZtEwOekM from "./images/mtnFacebookDaily1GbR20Png.png"; // plasmic-import: CTbGZtEWOekM/picture
import mtnFacebookDaily2GbR50PngW9HQErGec6Ty from "./images/mtnFacebookDaily2GbR50Png.png"; // plasmic-import: W9hQErGec6TY/picture
import mtnFacebookInstagramDaily250MbR7PngTzu09WcDcTgq from "./images/mtnFacebookInstagramDaily250MbR7Png.png"; // plasmic-import: TZU09WcDCTgq/picture
import mtnFacebookInstagramWeekly1GbR25PngLQnnGgA7Fljz from "./images/mtnFacebookInstagramWeekly1GbR25Png.png"; // plasmic-import: LQnnGgA7Fljz/picture
import mtnFacebookInstagramMonthly1GbR40Png3Z9UMr5Kk0Ha from "./images/mtnFacebookInstagramMonthly1GbR40Png.png"; // plasmic-import: 3z9uMr5Kk0HA/picture
import mtnSocialPassDaily300MBpngN2Tk7I1Mvd37 from "./images/mtnSocialPassDaily300MBpng.png"; // plasmic-import: N2tk7I1MVD37/picture
import mtnSocialPassWeekly1GbpngSYuj87RlfJNu from "./images/mtnSocialPassWeekly1Gbpng.png"; // plasmic-import: sYUJ87RlfJNu/picture
import mtnTikTokDaily200MbR5Png7OxKhs5Mo83 from "./images/mtnTikTokDaily200MbR5Png.png"; // plasmic-import: 7oxKhs5Mo_83/picture
import mtnTikTokWeeklyR20PngOtmzJ3YqEz7S from "./images/mtnTikTokWeeklyR20Png.png"; // plasmic-import: OtmzJ3yqEz7s/picture
import mtnTikTok1MonthpngMdnF7Jwwb1B from "./images/mtnTikTok1Monthpng.png"; // plasmic-import: _mdnF7jwwb1b/picture
import mtnYoutubeDailypngRJtjvjWdvDxo from "./images/mtnYoutubeDailypng.png"; // plasmic-import: RJtjvjWDVDxo/picture
import mtnYoutubeWeeklypng0H3YMh5YXvTq from "./images/mtnYoutubeWeeklypng.png"; // plasmic-import: 0H3yMH5yXvTQ/picture

createPlasmicElementProxy;

export const PlasmicMtnSocialBundles__VariantProps = new Array();

export const PlasmicMtnSocialBundles__ArgProps = new Array();

function PlasmicMtnSocialBundles__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshbagvQWqcZ69()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"shop"}
          data-plasmic-override={overrides.shop}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.shop
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <section className={classNames(projectcss.all, sty.section__gWWst)}>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#2E2854" }}
                      >
                        {"MTN Social Bundles"}
                      </span>
                    </React.Fragment>
                  </h1>
                }

                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__sqGYr)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__t9OnK)}
            >
              <div className={classNames(projectcss.all, sty.column__bVPdg)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6ZqDd)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWhatsAppDailypng2GjKo6Dzf507,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__xsb0E)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hxS5M)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: mtnWhatsAppWeekly300MbR12PngMtFiWaHg96SR,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__jum0C)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nngAu)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWhatsAppWeekly1GbR25PngMlv7YaIbPbvU,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___99Non)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dstY)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnWhatsAppMonthly1GbR40PngYwk3UJdOTuPv,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__cbLhz)}
            >
              <div className={classNames(projectcss.all, sty.column__cf9Aa)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__i95LQ)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnFacebookDaily200R5PngQyokoGuqQlYs,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__c1W40)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___2BbaC)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: mtnFacebookDaily1GbR20PngCTbGZtEwOekM,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___74RN6)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6Ki5R)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnFacebookDaily2GbR50PngW9HQErGec6Ty,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__nH8Aw)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cQ0Wd)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnFacebookInstagramDaily250MbR7PngTzu09WcDcTgq,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__j1NDu)}
            >
              <div className={classNames(projectcss.all, sty.column___0G56O)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__wnBeK)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: mtnFacebookInstagramWeekly1GbR25PngLQnnGgA7Fljz,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__k7TCw)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__a2Eii)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnFacebookInstagramMonthly1GbR40Png3Z9UMr5Kk0Ha,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__s6G4P)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rKrZ)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnSocialPassDaily300MBpngN2Tk7I1Mvd37,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__jAhrA)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ofYg4)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnSocialPassWeekly1GbpngSYuj87RlfJNu,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__fd0LL)}
            >
              <div className={classNames(projectcss.all, sty.column__daSut)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nA0Si)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: mtnSocialPassWeekly1GbpngSYuj87RlfJNu,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__xarxv)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__e11W5)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnTikTokDaily200MbR5Png7OxKhs5Mo83,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__hkfXv)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__el5Ho)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnTikTokWeeklyR20PngOtmzJ3YqEz7S,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__hl6YK)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mP5Rb)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnTikTok1MonthpngMdnF7Jwwb1B,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__v1Kgr)}
            >
              <div className={classNames(projectcss.all, sty.column__jkRMb)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zBL8)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: mtnYoutubeDailypngRJtjvjWdvDxo,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__hGY6)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ltKre)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnYoutubeWeeklypng0H3YMh5YXvTq,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___6C6LL)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__pL0M)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: mtnYoutubeWeeklypng0H3YMh5YXvTq,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__dHa1R)} />
            </p.Stack>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  shop: ["shop", "header", "text", "h1", "footer"],
  header: ["header"],
  text: ["text", "h1"],
  h1: ["h1"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMtnSocialBundles__ArgProps,
          internalVariantPropNames: PlasmicMtnSocialBundles__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMtnSocialBundles__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "shop") {
    func.displayName = "PlasmicMtnSocialBundles";
  } else {
    func.displayName = `PlasmicMtnSocialBundles.${nodeName}`;
  }
  return func;
}

export const PlasmicMtnSocialBundles = Object.assign(
  // Top-level PlasmicMtnSocialBundles renders the root element
  makeNodeComponent("shop"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    text: makeNodeComponent("text"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicMtnSocialBundles
    internalVariantProps: PlasmicMtnSocialBundles__VariantProps,
    internalArgProps: PlasmicMtnSocialBundles__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "MTN Data",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicMtnSocialBundles;
/* prettier-ignore-end */
