// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wdjrQSNRX7ys49KwqunuZ4
// Component: CgXHQPjcsQdv
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 7oMbG7rPxeuI/component
import Footer from "../../Footer"; // plasmic-import: t96iChT22ax_/component
import { useScreenVariants as useScreenVariantshbagvQWqcZ69 } from "../website_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: HbagvQWqcZ69/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../website_starter/plasmic_website_starter.module.css"; // plasmic-import: wdjrQSNRX7ys49KwqunuZ4/projectcss
import sty from "./PlasmicVodacomData.module.css"; // plasmic-import: CgXHQPjcsQdv/css
import vodacomDaily20MbR5PngENictA6BkE8 from "./images/vodacomDaily20MbR5Png.png"; // plasmic-import: eNictA6Bk-E8/picture
import vodacomDaily60MbR9Png3F0OsQr9LhYj from "./images/vodacomDaily60MbR9Png.png"; // plasmic-import: 3F0osQR9lhYJ/picture
import vodacomDaily100MbR15PngBRzifKrbzH8K from "./images/vodacomDaily100MbR15Png.png"; // plasmic-import: bRzifKrbzH8K/picture
import vodacomWeekly120MbR17PngYcStOOuJloht from "./images/vodacomWeekly120MbR17Png.png"; // plasmic-import: YcStOOuJloht/picture
import vodacomWeekly250MbR29PngHv2VzBwHcFvB from "./images/vodacomWeekly250MbR29Png.png"; // plasmic-import: HV2VZBwHcFvB/picture
import vodacomWeekly500MbR49PngUNlLUwlbwsrX from "./images/vodacomWeekly500MbR49Png.png"; // plasmic-import: UNlLUwlbwsrX/picture
import vodacomWeekly1GbWeeklyR69PngBaUhRcQJdWg5 from "./images/vodacomWeekly1GbWeeklyR69Png.png"; // plasmic-import: BAUhRcQJdWG5/picture
import vodacomWeekly2GbWeeklyR99PngEke5OdiIzumY from "./images/vodacomWeekly2GbWeeklyR99Png.png"; // plasmic-import: EKE5OdiIzumY/picture
import vodacomData50MbR12PngYiCguZyHug50 from "./images/vodacomData50MbR12Png.png"; // plasmic-import: YICguZYHug50/picture
import vodacomData200MbR29PngIPzJQeKIiViZ from "./images/vodacomData200MbR29Png.png"; // plasmic-import: IPzJQeKIiViZ/picture
import vodacomData500MbR69PngOjbsaElMlZp from "./images/vodacomData500MbR69Png.png"; // plasmic-import: ojbsa-ELMlZp/picture
import vodacomData1GbR85PngJg0NG0H8HvM from "./images/vodacomData1GbR85Png.png"; // plasmic-import: Jg0n-g0h8hvM/picture
import vodacomData2GbR149PngDyaqi30FFvRn from "./images/vodacomData2GbR149Png.png"; // plasmic-import: Dyaqi30fFvRN/picture
import vodacomData4GbR249PngAomkBaVwVmUh from "./images/vodacomData4GbR249Png.png"; // plasmic-import: AOMKBaVwVMUh/picture
import vodacomData6GbR349PngSUnUMZslC3G from "./images/vodacomData6GbR349Png.png"; // plasmic-import: SUnU_MZslC3G/picture
import vodacomData10GbR469CopypngWjgme7R29ZrU from "./images/vodacomData10GbR469Copypng.png"; // plasmic-import: Wjgme7R29ZrU/picture
import vodacomData15GbR529PngE1CPURnyRnf from "./images/vodacomData15GbR529Png.png"; // plasmic-import: e1cP_uRnyRNF/picture
import vodacomData30GbR699Png2EE3KdKpGhs from "./images/vodacomData30GbR699Png.png"; // plasmic-import: 2eE3kd_KpGhs/picture

createPlasmicElementProxy;

export const PlasmicVodacomData__VariantProps = new Array();

export const PlasmicVodacomData__ArgProps = new Array();

function PlasmicVodacomData__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshbagvQWqcZ69()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"shop"}
          data-plasmic-override={overrides.shop}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.shop
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <section className={classNames(projectcss.all, sty.section__jcic7)}>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#2E2854" }}
                      >
                        {"Vodacom Data"}
                      </span>
                    </React.Fragment>
                  </h1>
                }

                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__yJ3Fq)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__aJjWc)}
            >
              <div className={classNames(projectcss.all, sty.column__vXfFj)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mveeU)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: vodacomDaily20MbR5PngENictA6BkE8,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__c3NWw)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cbG8B)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomDaily60MbR9Png3F0OsQr9LhYj,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__eSjv)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__twgD)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomDaily100MbR15PngBRzifKrbzH8K,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___25C2)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__aNdfv)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomWeekly120MbR17PngYcStOOuJloht,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__hdh5M)}
            >
              <div className={classNames(projectcss.all, sty.column__k5Ep)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fYuJm)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: vodacomWeekly250MbR29PngHv2VzBwHcFvB,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__tcfKo)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hOzxo)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomWeekly500MbR49PngUNlLUwlbwsrX,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__hlS4Q)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__jeuF)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomWeekly1GbWeeklyR69PngBaUhRcQJdWg5,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wwrfD)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gfz1T)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomWeekly2GbWeeklyR99PngEke5OdiIzumY,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___22Sey)}
            >
              <div className={classNames(projectcss.all, sty.column__zrCCk)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gktA9)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: vodacomData50MbR12PngYiCguZyHug50,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__lsiEo)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__oGnNu)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomData200MbR29PngIPzJQeKIiViZ,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__mIWeB)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__l1K)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomData500MbR69PngOjbsaElMlZp,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__aDFl)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bDiZg)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomData1GbR85PngJg0NG0H8HvM,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__rcwzN)}
            >
              <div className={classNames(projectcss.all, sty.column___2JRhI)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__tfRhs)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: vodacomData2GbR149PngDyaqi30FFvRn,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__u9Suy)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__wlR3)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomData4GbR249PngAomkBaVwVmUh,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__qGt6F)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__lPm7G)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomData6GbR349PngSUnUMZslC3G,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__z2Agb)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fpRBv)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomData10GbR469CopypngWjgme7R29ZrU,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___1U6Hs)}
            >
              <div className={classNames(projectcss.all, sty.column__rm0W)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__y4Fj)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: vodacomData15GbR529PngE1CPURnyRnf,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__clFEm)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___4PcFu)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomData30GbR699Png2EE3KdKpGhs,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___633TG)} />
              <div className={classNames(projectcss.all, sty.column__hcusf)} />
            </p.Stack>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  shop: ["shop", "header", "text", "h1", "footer"],
  header: ["header"],
  text: ["text", "h1"],
  h1: ["h1"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicVodacomData__ArgProps,
          internalVariantPropNames: PlasmicVodacomData__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVodacomData__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "shop") {
    func.displayName = "PlasmicVodacomData";
  } else {
    func.displayName = `PlasmicVodacomData.${nodeName}`;
  }
  return func;
}

export const PlasmicVodacomData = Object.assign(
  // Top-level PlasmicVodacomData renders the root element
  makeNodeComponent("shop"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    text: makeNodeComponent("text"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicVodacomData
    internalVariantProps: PlasmicVodacomData__VariantProps,
    internalArgProps: PlasmicVodacomData__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Vodacom Data",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicVodacomData;
/* prettier-ignore-end */
