// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wdjrQSNRX7ys49KwqunuZ4
// Component: MNCcrrk_j-sr
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 7oMbG7rPxeuI/component
import Footer from "../../Footer"; // plasmic-import: t96iChT22ax_/component
import { useScreenVariants as useScreenVariantshbagvQWqcZ69 } from "../website_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: HbagvQWqcZ69/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../website_starter/plasmic_website_starter.module.css"; // plasmic-import: wdjrQSNRX7ys49KwqunuZ4/projectcss
import sty from "./PlasmicVodacomAirtime.module.css"; // plasmic-import: MNCcrrk_j-sr/css
import vodacomAirtimeR2PngPDw8GFzKh0YB from "./images/vodacomAirtimeR2Png.png"; // plasmic-import: PDw8GFzKh0yB/picture
import vodacomAirtimeR5PngCTtdkQsDXs from "./images/vodacomAirtimeR5Png.png"; // plasmic-import: cTtdk__QsDXs/picture
import vodacomAirtimeR10PngVBslPreF2Lvb from "./images/vodacomAirtimeR10Png.png"; // plasmic-import: vBslPreF2lvb/picture
import vodacomAirtimeR12PngUUgdiRiykq5D from "./images/vodacomAirtimeR12Png.png"; // plasmic-import: uUGDIRiykq5D/picture
import vodacomAirtimeR29PngCyX3Z66Eub0U from "./images/vodacomAirtimeR29Png.png"; // plasmic-import: cyX3Z66Eub0u/picture
import vodacomAirtimeR55PngWpizUIvesa0 from "./images/vodacomAirtimeR55Png.png"; // plasmic-import: Wpiz-uIvesa0/picture
import vodacomAirtimeR110PngQAgOa8HMon5 from "./images/vodacomAirtimeR110Png.png"; // plasmic-import: qAgOa8hMON_5/picture
import vodacomAirtimeR275Png5VyC18GVmTn from "./images/vodacomAirtimeR275Png.png"; // plasmic-import: 5vyC18-GVmTN/picture

createPlasmicElementProxy;

export const PlasmicVodacomAirtime__VariantProps = new Array();

export const PlasmicVodacomAirtime__ArgProps = new Array();

function PlasmicVodacomAirtime__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshbagvQWqcZ69()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"shop"}
          data-plasmic-override={overrides.shop}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.shop
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <section className={classNames(projectcss.all, sty.section__npmnY)}>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#2E2854" }}
                      >
                        {"Vodacom Airtime"}
                      </span>
                    </React.Fragment>
                  </h1>
                }

                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__gXdle)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__vscfb)}
            >
              <div className={classNames(projectcss.all, sty.column___7Jysi)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___7DvhD)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: vodacomAirtimeR2PngPDw8GFzKh0YB,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__eo3Xu)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__a6Yal)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomAirtimeR5PngCTtdkQsDXs,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wonXz)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__sFxSd)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomAirtimeR10PngVBslPreF2Lvb,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__qXChB)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dlauR)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomAirtimeR12PngUUgdiRiykq5D,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__jcOqb)}
            >
              <div className={classNames(projectcss.all, sty.column___1VqWx)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__c725K)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "500px"
                      : "auto"
                  }
                  loading={"lazy"}
                  src={{
                    src: vodacomAirtimeR29PngCyX3Z66Eub0U,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__m2TiT)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___3CDa)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomAirtimeR55PngWpizUIvesa0,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__eaWNv)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___2SlEc)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomAirtimeR110PngQAgOa8HMon5,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__va3Rn)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___9PzL6)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: vodacomAirtimeR275Png5VyC18GVmTn,
                    fullWidth: 408,
                    fullHeight: 408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  shop: ["shop", "header", "text", "h1", "footer"],
  header: ["header"],
  text: ["text", "h1"],
  h1: ["h1"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicVodacomAirtime__ArgProps,
          internalVariantPropNames: PlasmicVodacomAirtime__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVodacomAirtime__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "shop") {
    func.displayName = "PlasmicVodacomAirtime";
  } else {
    func.displayName = `PlasmicVodacomAirtime.${nodeName}`;
  }
  return func;
}

export const PlasmicVodacomAirtime = Object.assign(
  // Top-level PlasmicVodacomAirtime renders the root element
  makeNodeComponent("shop"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    text: makeNodeComponent("text"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicVodacomAirtime
    internalVariantProps: PlasmicVodacomAirtime__VariantProps,
    internalArgProps: PlasmicVodacomAirtime__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Vodacom Airtime",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicVodacomAirtime;
/* prettier-ignore-end */
